import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {A11yModule} from '@angular/cdk/a11y';
import {BidiModule} from '@angular/cdk/bidi';
import {ObserversModule} from '@angular/cdk/observers';
import {OverlayModule} from '@angular/cdk/overlay';
import {PlatformModule} from '@angular/cdk/platform';
import {PortalModule} from '@angular/cdk/portal';
import {ScrollDispatchModule} from '@angular/cdk/scrolling';
import {CdkStepperModule} from '@angular/cdk/stepper';
import {CdkTableModule} from '@angular/cdk/table';

import {
	MatProgressSpinnerModule,
	MatDialogModule,
	MatButtonModule,
	MatCheckboxModule,
	MatPaginatorModule,
	MatSortModule,
	MatTableModule,
	MatExpansionModule,
	MatFormFieldModule,
	MatInputModule,
	MatTabsModule,
	MatSelectModule,
	MatAutocompleteModule,
	MatButtonToggleModule,
	MatCardModule,
	MatChipsModule,
	MatDatepickerModule,
	MatGridListModule,
	MatIconModule,
	MatListModule,
	MatMenuModule,
	MatNativeDateModule,
	MatProgressBarModule,
	MatRadioModule,
	MatRippleModule,
	MatSidenavModule,
	MatSliderModule,
	MatSlideToggleModule,
	MatSnackBarModule,
	MatStepperModule,
	MatToolbarModule,
	MatTooltipModule,
	MatRipple,
} from '@angular/material';

@NgModule({
  	imports: [
		MatProgressSpinnerModule,
		MatDialogModule,
		MatButtonModule,
		MatCheckboxModule,
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
		MatExpansionModule,
		MatFormFieldModule,
		MatInputModule,
		MatTabsModule,
		MatSelectModule,
		MatAutocompleteModule,
		MatButtonToggleModule,
		MatCardModule,
		MatChipsModule,
		MatDatepickerModule,
		MatGridListModule,
		MatIconModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressBarModule,
		MatRadioModule,
		MatRippleModule,
		MatSidenavModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatStepperModule,
		MatToolbarModule,
		MatTooltipModule,
		MatButtonModule,
		MatCheckboxModule,
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
		MatExpansionModule,
		BrowserAnimationsModule,
		MatFormFieldModule,
		MatInputModule,
		MatTabsModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatSelectModule,
		MatIconModule,

		A11yModule,
		BidiModule,
		ObserversModule,
		OverlayModule,
		PlatformModule,
		PortalModule,
		ScrollDispatchModule,
		CdkStepperModule,
		CdkTableModule,
	],
  	exports: [
		MatProgressSpinnerModule,
		MatDialogModule,
		MatButtonModule,
		MatCheckboxModule,
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
		MatExpansionModule,
		MatFormFieldModule,
		MatInputModule,
		MatTabsModule,
		MatSelectModule,
		MatAutocompleteModule,
		MatButtonToggleModule,
		MatCardModule,
		MatChipsModule,
		MatDatepickerModule,
		MatGridListModule,
		MatIconModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressBarModule,
		MatRadioModule,
		MatRippleModule,
		MatSidenavModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatStepperModule,
		MatToolbarModule,
		MatTooltipModule,
		MatButtonModule,
		MatCheckboxModule,
		MatPaginatorModule,
		MatSortModule,
		MatTableModule,
		MatExpansionModule,
		BrowserAnimationsModule,
		MatFormFieldModule,
		MatInputModule,
		MatTabsModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatSelectModule,
		MatIconModule,

		A11yModule,
		BidiModule,
		ObserversModule,
		OverlayModule,
		PlatformModule,
		PortalModule,
		ScrollDispatchModule,
		CdkStepperModule,
		CdkTableModule,
	  ],
	  providers: [ MatRipple ]
})
export class MaterialModule { }
